name: Pod Exposer
description: Returns the Build Pod's Name.

outputs:
  pod_name:
    description: Pod Name
    value: ${{ steps.pod_name.outputs.pod_name }}

runs:
  using: 'composite'
  steps:
    - name: Expose pod name
      id: pod_name
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        script_output=$(python "${{ github.action_path }}/pod_exposer.py")
        echo "pod_name=$script_output" >> $GITHUB_OUTPUT
